DOCS-330: Continuing Clean Up Work
minio/docs pull request #337
Opened 2021-04-14 00:43 UTC by ravindk89

# Summary

This is the last component of DOCS-330. This should include all core information previously covered between github and docs.min.io. 

# Goals

- Unified active-passive and active-active security sections, minor touch-ups
- Imported sections on behavior for server-side replication, delete replication, sync/async, etc.

# Non-Goals

- More diagrams
- Examples for `mc replicate`

# Build Instructions

The MinIO docs require Python 3.9+ and Node for building. For Node, use v14.5.0 or later.

1) Clone the repo, Checkout the branch (`git checkout -B DOCS-324 origin/DOCS-324`)
2) Run `npm install` from the branch
3) Create a python venv (`python -m venv venv`)
4) Install requirements (`pip install -r requirements.txt`)
5) Run `make html`
6) Run `python -m http.server --directory build/DOCS-324/html`
7) Open 127.0.0.1:8000 in your browser and take a poke around.

If you run into an error running `python -m http.server` related to `--directory`, you're python version is likely older. CD into the `build/<branch>/html` directory and run the command without the `--directory` argument.

# Key URLS

- http://127.0.0.1:8000/replication/replication-overview.html
- http://127.0.0.1:8000/replication/enable-server-side-two-way-bucket-replication.html
- - http://127.0.0.1:8000/replication/enable-server-side-one-way-bucket-replication.html

2021-04-14 00:45 UTC, ravindk89 commented
@poornas @vadmeste there is one more "chunk" missing here related to the replication queue. Copying over the gaps from slack:

1. Is the replication queue global or per bucket?
2. Is the replication queue size configurable?
3. Is the 10K queue size for all 100 workers, or per worker? 
4. What are the potential ramifications of increasing workers? 
5. Does synchronous replication rely on the replication queue? That is, if the queue is full, will synchronized replication wait until a worker gets to it? 
6. Is the replication queue FIFO ? that is, workers move in order of the queue from first to last.

2021-04-14 17:56 UTC, poornas requested changes

2021-04-14 18:11 UTC, ravindk89 commented on source/replication/enable-server-side-one-way-bucket-replication.rst
> +                        "s3:PutObjectLegalHold",
Done in both procedures

2021-04-14 18:11 UTC, ravindk89 commented on source/replication/enable-server-side-two-way-bucket-replication.rst
> +planning required for this implementation.
Refined based on convo in slack.

2021-04-15 05:56 UTC, poornas approved these changes
LGTM

2021-04-15 15:54 UTC, merged