DOCS-339: MinIO ILM Migration + Tiering
minio/docs pull request #342
Opened 2021-05-03 23:56 UTC by ravindk89

# Summary

Create and update reference documentation + tutorials for MinIO ILM + Remote Tiers

# Goals
- Refresh `mc ilm` for missed updates
- Add `mc admin remote` command
- Add tutorials for transitioning objects to s3, gcs, azure
- Add tutorial for object expiration
- Create landing page for object lifecycle management

# Non-Goals

- Complete cleanup of reference pages

# Build Instructions

The MinIO docs require Python 3.9+ and Node for building. For Node, use v14.5.0 or later.

1) Clone the repo, Checkout the branch (`git checkout -B installation-fixes origin/DOCS-339`)
2) Run `npm install` from the branch
3) Create a python venv (`python -m venv venv`)
4) Install requirements (`pip install -r requirements.txt`)
5) Run `make html`
6) Run `python -m http.server --directory build/DOCS-339/html`
7) Open 127.0.0.1:8000 in your browser and take a poke around.

If you run into an error running `python -m http.server` related to `--directory`, you're python version is likely older. CD into the `build/<branch>/html` directory and run the command without the `--directory` argument.

# Key URLS

- http://127.0.0.1:8000/lifecycle-management/lifecycle-management-overview.html
- http://127.0.0.1:8000/lifecycle-management/create-lifecycle-management-expiration-rule.html
- http://127.0.0.1:8000/lifecycle-management/transition-objects-to-s3.html
- http://127.0.0.1:8000/lifecycle-management/transition-objects-to-gcs.html
- http://127.0.0.1:8000/lifecycle-management/transition-objects-to-azure.html
- http://127.0.0.1:8000/reference/minio-cli/minio-mc/mc-ilm.html#mc-ilm-add
- http://127.0.0.1:8000/reference/minio-cli/minio-mc-admin/mc-admin-tier.html

2021-05-03 23:57 UTC, ravindk89 commented on source/includes/common-minio-tiering.rst
> +Use the :mc-cmd:`mc ilm add` command to create a new transition rule
This chunk gets included in all three of the transition tutorials as part of the step for creating the new transition rules.

2021-05-03 23:57 UTC, ravindk89 commented on source/includes/common-minio-tiering.rst
> +This step creates users and policies on the MinIO deployment for supporting
This chunk gets included in the step where users create users/policies.

2021-05-03 23:57 UTC, ravindk89 commented on source/includes/common-minio-tiering.rst
> +   wget -O - https://docs.min.io/minio/baremetal/examples/LifecycleManagementAdmin.json | \
This wont work until I merge to master :/ sorry!

2021-05-03 23:58 UTC, ravindk89 commented on source/includes/common-minio-tiering.rst
> +   wget -O - https://docs.min.io/minio/baremetal/examples/LifecycleManagementAdmin.json | \
If you want to cheat, change the URL to the python server root instead

2021-05-04 21:10 UTC, poornas requested changes

2021-05-04 21:39 UTC, krisis commented on source/lifecycle-management/lifecycle-management-overview.rst
> +MinIO automatically moves the object to a configured remote S3 storage
```suggestion
MinIO automatically moves the object to a configured remote storage
```

2021-05-04 21:39 UTC, krisis commented on source/lifecycle-management/lifecycle-management-overview.rst
> +and conversion to or from XMl may be required.
nit: typo
```suggestion
and conversion to or from XML may be required. 
```

2021-05-04 21:39 UTC, krisis commented on source/lifecycle-management/lifecycle-management-overview.rst
> +"expiration" involves performing a ``DELETE`` operation on the bucket. For
```suggestion
"expiration" involves performing a ``DELETE`` operation on the object. For 
```

2021-05-04 21:39 UTC, krisis commented on source/lifecycle-management/transition-objects-to-azure.rst
> +Defer to the `Azure RBAC
nit: typo
```suggestion
Refer to the `Azure RBAC
```

2021-05-04 23:38 UTC, ravindk89 commented on source/reference/minio-cli/minio-mc/mc-ilm.rst
> +      datetime marks all objects covered by the rule for transition.
Hm - that would make sense for transition-days, but not transition-date. I'm not sure what I was thinking here, so I'll remove this.

2021-05-04 23:38 UTC, ravindk89 commented on source/reference/minio-cli/minio-mc/mc-ilm.rst
> +      datetime marks all objects covered by the rule for transition.
Hm - that would make sense for transition-days, but not transition-date. I'm not sure what I was thinking here, so I'll remove this.

2021-05-04 23:40 UTC, krisis commented on source/lifecycle-management/lifecycle-management-overview.rst
> +data to a supported Cloud Service Provider storage backend. You can then use the
Suggestion
```suggestion
data to a supported Cloud Service Provider object storage You can then use the
```

2021-05-04 23:40 UTC, krisis commented on source/reference/minio-cli/minio-mc-admin/mc-admin-tier.rst
> +      have permission to perform read/write/list operations on the
```suggestion
      have permission to perform read/write/list/delete operations on the 
```

2021-05-04 23:40 UTC, krisis commented on source/reference/minio-cli/minio-mc-admin/mc-admin-tier.rst
> +      must have permission to perform read/write/list operations on the
```suggestion
      must have permission to perform read/write/list/delete operations on the
```

2021-05-04 23:40 UTC, krisis commented on source/reference/minio-cli/minio-mc-admin/mc-admin-tier.rst
> +      read/write/list operations on the remote bucket or bucket prefix.
```suggestion
      read/write/list/delete operations on the remote bucket or bucket prefix.
```

2021-05-04 23:40 UTC, krisis commented on source/reference/minio-cli/minio-mc-admin/mc-admin-tier.rst
> +      have permission to perform read/write/list operations on the
```suggestion
      have permission to perform read/write/list/delete operations on the 
```

2021-05-04 23:40 UTC, krisis commented on source/reference/minio-cli/minio-mc-admin/mc-admin-tier.rst
> +      must have permission to perform read/write/list operations on the
```suggestion
      must have permission to perform read/write/list/delete operations on the
```

2021-05-04 23:40 UTC, krisis commented on source/reference/minio-cli/minio-mc-admin/mc-admin-tier.rst
> +      permission to perform read/write/list operations on the remote bucket
```suggestion
      permission to perform read/write/list/delete operations on the remote bucket
```

2021-05-04 23:40 UTC, krisis commented on source/reference/minio-cli/minio-mc-admin/mc-admin-tier.rst
> +   .. mc-cmd:: account-
```suggestion
   .. mc-cmd:: account-name
```

2021-05-04 23:40 UTC, krisis commented on source/lifecycle-management/transition-objects-to-gcs.rst
> +Defer to the `GCS IAM permissions
```suggestion
Refer to the `GCS IAM permissions
```

2021-05-04 23:40 UTC, krisis commented on source/lifecycle-management/transition-objects-to-s3.rst
> +Defer to the :aws-docs:`Amazon S3 Permissions
```suggestion
Refer to the :aws-docs:`Amazon S3 Permissions 
```

2021-05-05 18:11 UTC, krisis approved these changes

2021-05-05 21:55 UTC, poornas approved these changes
LGTM

2021-05-05 23:00 UTC, ravindk89 commented
Holding off on merging until we have the latest release of `minio` + and the `mc` changes from the pending PR on `mc admin tier`.

2021-05-12 14:20 UTC, merged