#346 Adding info for parsing JSON for srsARN value
minio/docs pull request #449
Opened 2022-03-23 20:43 UTC by djwfyi

Closes #346

Adds a new include file for bucket notification ARN identification.
Modifies each `publish` file under `monitoring/bucket-notifications` to add include file and a substitution directive.

2022-03-24 16:23 UTC, ravindk89 requested changes
Minor nits and one open point of discussion.

Also you man need to add `.DS_Store` to the `.gitignore` file, I think that is coming from osx.

2022-03-24 18:26 UTC, djwfyi commented on source/includes/bucket-notifications-find-arn.rst
> +.. admonition:: Identifying the ARN for your bucket notifications
I can see the logic of doing things in a common file with the `start-after` and `end-before` fences.

2022-03-24 18:29 UTC, djwfyi commented on source/includes/bucket-notifications-find-arn.rst
> +   You defined the target ARN for your bucket notifications when creating the endpoint in step 1.
Updating line 4 to

> You defined the name to assign to the target ARN for your bucket notifications when creating the endpoint in step 1.
> The command options below allow you to find the entire target ARN.

2022-03-24 18:30 UTC, djwfyi commented on source/monitoring/bucket-notifications/publish-events-to-elasticsearch.rst
> +.. |ARN| replace:: ``arn:minio:sqs::primary:Elasticsearch``
The capital E in `Elasticsearch` for the resource in the ARN is how the ARN displays throughout the rest of the file.
I did not update all the instances of the ARN in the file to use the substitution.

2022-03-24 18:47 UTC, ravindk89 commented on source/includes/common-bucket-notifications.rst
> +   The command options below allow you to find the entire target ARN.
"The steps below return all configured ARNs on the deployment. Identify the ARN created in step 1 using the name you specified (``IDENTIFIER``)"

Or something.

2022-03-24 18:48 UTC, ravindk89 commented on source/includes/common-bucket-notifications.rst
> +      The ARN you need is the value of that key, such as |ARN|
Same thought specifying it's the ARN that matches both the name + service as specified in step 1

2022-03-24 18:48 UTC, ravindk89 approved these changes
Two optional nits, otherwise LGTM.

2022-03-28 15:25 UTC, harshavardhana requested changes
Please remove the .DS_store file from the commit

2022-03-28 15:28 UTC, ravindk89 commented
Ah we added that to `.gitignore` in another commit.

Should be fine to add it here, it should all get settled with the rebase

2022-03-28 16:05 UTC, ravindk89 approved these changes
LGTM. If there's some nits or grits left we can deal with them in another pass.

2022-03-28 16:05 UTC, merged