DOCS-492: Container Platform Docs
minio/docs pull request #510
Opened 2022-07-13 22:31 UTC by ravindk89

# Summary

This commit adds a `make container` build for Docker/Podman

This commit also generally cleans up the Installation docs and uses /includes/<platform>/steps-*.rst as a pattern for storing platform-specific tutorials within a single root URL.

Finally, due to API rate limits, this commit adds some Makefile magic to allow skipping of sync'ing dependencies. Pass `make BUILD_DEPENDENCIES=FALSE <platform>` to skip building any deps and use what is already in the branch.

# Notes

This PR will require a refresh once my API restrictions fall off such that the various SDK docs are not negatively impacted. Please ignore the massive swath of deletions.

No staging links available yet, as my local builds are slightly broken. Will update once the API limit drops.

2022-07-13 22:32 UTC, ravindk89 commented on Makefile
> -SPHINXOPTS    ?= -n -j "auto"
Logs output to a text file so it's easier to track what has gone wrong. Already excluded from git.

2022-07-13 22:32 UTC, ravindk89 commented on Makefile
> +ifeq ($(BUILD_SDK),FALSE)
Typo, should be `BUILD_DEPENDENCIES`, will fix on next commit pass.

2022-07-13 22:34 UTC, ravindk89 commented on source/default-conf.py
> +        'operations/install-deploy-manage/multi-site-replication.rst',
Intentionally excluded in this pass.

- Distributed deploys via containers should be done via K8s. We will not be publishing docs for compose, swarm, helm, etc.
- Multi-Site can be handled in a separate pass if at all, as container networking makes this very finicky.

2022-07-13 22:35 UTC, ravindk89 commented on source/operations/install-deploy-manage/deploy-minio-single-node-multi-drive.rst
> -3) Add TLS Certificates
Intentionally dropped, as the dedicated TLS tutorial page can provide better instructions. If we want to go this route, it should be as part of a polish pass where the deploy tutorials cover *all* possible setups, including TLS, KES, etc. That requires significantly more effort and care than we have bandwidth for today.

2022-07-14 21:57 UTC, djwfyi requested changes
Missing content for Windows in the SNMD page.
Some suggestions for repetitive content that would be great to move into a more single sourced mechanism.

Other bits for spelling, punctuation, or clarity throughout.

I'll take another look after those are done.

2022-07-14 21:57 UTC, djwfyi commented on source/includes/macos/steps-deploy-minio-single-node-single-drive.rst
> +1) Download the MinIO Server
Not going to relist them, but this needs the same fixes as the other files.

2022-07-14 21:57 UTC, djwfyi commented on source/operations/install-deploy-manage/deploy-minio-single-node-multi-drive.rst
> +   .. include:: /includes/macos/steps-deploy-minio-single-node-multi-drive.rst
Windows content is missing.
Need to add the windows conditional and content.

2022-07-14 21:57 UTC, djwfyi commented on source/operations/install-deploy-manage/deploy-minio-single-node-multi-drive.rst
>  .. admonition:: Network File System Volumes Break Consistency Guarantees
This admonition is really repetitive to the one just above it on the page. (Lines 36-44 are basically the same, and there's just a heading and one line paragraph between them.)

2022-07-15 19:44 UTC, ravindk89 reviewed
@djwfyi back to you. Significant single sourcing pass. Skipping Windows as I need to verify how that all behaves first.

2022-07-15 19:44 UTC, ravindk89 commented on source/operations/install-deploy-manage/deploy-minio-single-node-single-drive.rst
>  See :ref:`minio-snsd-pre-existing-data <minio-snsd-pre-existing-data>` for more complete documentation on MinIO startup behavior in |SNSD| mode.
Done

2022-07-18 20:48 UTC, djwfyi requested changes
Minor nits.
One bad path that looks like a possible paste error.

Several of the comments are about using a variable in example output so that the file stays up-to-date automatically. But then we have to think about the copyright year line in each case.

Is there an issue for adding the Windows content?

Other than that, this LGTM after those fixes.

2022-07-18 20:48 UTC, djwfyi commented on source/includes/container/steps-deploy-minio-single-node-multi-drive.rst
> +   Version: RELEASE.2022-07-08T00-05-23Z (go1.18.3 linux/amd64)
Is it worth adding a substitution to this code block so you can use `|minio-latest|`?

If so, we'd need to figure out what we're going to do with line 133 each January.

2022-07-18 20:48 UTC, djwfyi commented on source/includes/container/steps-deploy-minio-single-node-single-drive.rst
> +   Version: RELEASE.2022-07-08T00-05-23Z (go1.18.3 linux/amd64)
Same question here. Use the global variable from `conf.py`?
Need to consider what happens to line 130 each January.

2022-07-18 20:48 UTC, djwfyi commented on source/includes/linux/steps-deploy-minio-single-node-multi-drive.rst
> +   Version: RELEASE.2022-07-08T00-05-23Z (go1.18.3 linux/amd64)
Variables?
Line 38?

2022-07-18 20:48 UTC, djwfyi commented on source/includes/linux/steps-deploy-minio-single-node-single-drive.rst
> +   Version: RELEASE.2022-07-08T00-05-23Z (go1.18.3 linux/amd64)
Variable here?
Line 38?

2022-07-18 20:48 UTC, djwfyi commented on source/operations/install-deploy-manage/deploy-minio-single-node-single-drive.rst
> +For extended development or production environments, deploy MinIO in :guilabel:`Distributed Mode`. See :ref:`deploy-minio-distributed` for mo/operations/install-deploy-manage/multi-site-replicationre
Need to fix this paste. The path is not in the :ref: link and splitting the word `more` instead.

2022-07-18 21:46 UTC, djwfyi approved these changes
LGTM

2022-07-18 21:46 UTC, merged