Initial work for git-managed redirects
minio/docs pull request #556
Opened 2022-09-12 22:18 UTC by ravindk89

This is the initial work for what should be a git-managed set of nginx configs we can include into the Nginx Docs server.

The idea here is we manage redirects in git, and either chron-copy them to a location we can include via the sites-available/<file>, *or* we just include them from the git path (if nginx tolerates that)

I can't really _test_ these right now since they are using live URLs. if we move forward with the soft-launch, we'll have a few opportunities to maybe test a subset of these URLs and see what happens.

Please let me know if there is anything *obviously* wrong here.

ToDo: The Legacy Docs redirects

2022-09-19 22:06 UTC, ravindk89 commented
So this is a little misleading, as none of these redirects go on the min.io server.

Instead these all get loaded in on the docs.min.io server, and handle redirects there.

If this all looks good, then we're basically one `systemctl restart nginx` away from pushing traffic over.

2022-09-20 14:42 UTC, djwfyi requested changes
Worth doing a find/replace on all of the redirect files to swap
min.io/minio/docs 
for
`min.io/docs/minio

I found some links to docs.min.io pages, so suggested replacements for those.
Might also consider doing a search in the docs for any other references to `docs.min.io`.

And some miscellaneous URL change suggestions throughout.

2022-09-20 14:42 UTC, djwfyi commented on redirects/windows.nginx
> +     return 301 https://min.io/minio/docs/windows/operations/index.html?ref=docs-redirect;
Folders swapped.
`min.io/docs/minio/windows` ....

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/aws-cli-with-minio.md
> +Install MinIO Server from [here](https://docs.min.io).
Need to fix this URL.

https://min.io/docs/minio/linux/reference/minio-server/minio-server.html, I suppose.

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/aws-cli-with-minio.md
> +# AWS CLI with MinIO Server [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io)
Why the Slack link in the page title?

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/disaggregated-spark-and-hadoop-hive-with-minio.md
> +  - [Deployment based on Kubernetes](https://docs.min.io/docs/deploy-minio-on-kubernetes.html#minio-distributed-server-deployment)
Maybe https://min.io/docs/minio/kubernetes/upstream/operations/installation.html instead.

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/disaggregated-spark-and-hadoop-hive-with-minio.md
> +  - [Deployment based on Kubernetes](https://docs.min.io/docs/deploy-minio-on-kubernetes.html#minio-distributed-server-deployment)
Oh, guess this can be a `:ref:` link.

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/generate-lets-encrypt-certificate-using-certbot-for-minio.md
> +# Generate Let's Encrypt certificate using Certbot for MinIO [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io)
Do we need a Slack link in the page title?
Also, add a line break after the title. Uh, please.

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/generate-lets-encrypt-certificate-using-certbot-for-minio.md
> +- Install MinIO Server from [here](https://docs.min.io/docs/minio-quickstart-guide).
Can we do :ref: links in .md files?
Otherwise, https://min.io/docs/minio/linux/reference/minio-server/minio-server.html

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/presigned-put-upload-via-browser.md
> +# Upload Files Using Pre-signed URLs [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io)
Slack link in title?

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/presigned-put-upload-via-browser.md
> +This guide describes how to use the [`presignedPutObject`](https://docs.min.io/docs/javascript-client-api-reference#presignedPutObject) API from the [MinIO JavaScript Library](https://github.com/mini
Update URL to:
https://min.io/docs/minio/linux/developers/javascript/API.html#presignedputobject-bucketname-objectname-expiry-callback

Also, noticed that the JavaScript SDK description is linking to the docs.min.io site. We need to scrub the SDK .md files for those URLs. Probably a separate issue, though.

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/setup-nginx-proxy-with-minio.md
> +# Set up Nginx proxy with MinIO Server [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io)
Slack link in title?

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/setup-nginx-proxy-with-minio.md
> +Install MinIO Server from [here](https://docs.min.io/docs/minio-quickstart-guide).
https://min.io/docs/minio/linux/reference/minio-server/minio-server.html

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/using-minio-with-veeam.md
> +- MinIO object storage set up per <https://docs.min.io/docs/minio-quickstart-guide.html>
https://min.io/docs/minio/linux/operations/network-encryption.html

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/using-minio-with-veeam.md
> +- Veeam requires TLS connections to the object storage.  This can be configured per <https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls.html>
https://min.io/docs/minio/linux/operations/network-encryption.html

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/using-minio-with-veeam.md
> +- Configure the minio client for the Veeam MinIO endpoint - <https://docs.min.io/docs/minio-client-quickstart-guide.html>
https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart

2022-09-20 14:42 UTC, djwfyi commented on source/integrations/using-minio-with-veeam.md
> +> Object locking requires erasure coding enabled on the minio server. For more information see <https://docs.minio.io/docs/minio-erasure-code-quickstart-guide.html>.
https://min.io/docs/minio/linux/operations/concepts/erasure-coding.html#

2022-09-20 14:42 UTC, djwfyi commented on redirects/linux.nginx
> +     return 301 https://min.io/minio/docs/linux/operations/concepts.html?ref=docs-redirect;
Looks like many of these links have the URL folders swapped.
Replace `min.io/minio/docs` with `min.io/docs/minio` throughout.

2022-09-20 14:42 UTC, djwfyi commented on redirects/linux.nginx
> +     return 301 https://min.io/minio/docs/linux/administration/bucket-replication/enable-server-side-one-way-bucket-replication.html?ref=docs-redirect;
THis should go to
https://min.io/docs/minio/linux/administration/bucket-replication/enable-server-side-multi-site-bucket-replication.html

2022-09-20 14:42 UTC, djwfyi commented on redirects/linux.nginx
> +     return 301 https://min.io/minio/docs/linux/administration/monitoring.html?ref=docs-redirect;
https://min.io/docs/minio/linux/administration/monitoring/bucket-notifications.html might be better.

2022-09-20 14:42 UTC, djwfyi commented on redirects/linux.nginx
> +location /minio/baremetal/reference/minio-mc/ {
`/minio/baremetal/reference/minio-mc-admin/`

Otherwise, this is a repeat of line 291.

2022-09-20 16:27 UTC, merged