Procedure for updating Operator
minio/docs pull request #608
Opened 2022-10-10 22:05 UTC by ravindk89

# Summary

This is a core upgrade procedure for the MinIO Operator. It focuses on using ``kubectl minio init`` as a baseline.

It also imports Oscar's work for the 3.X.X -> 4.2.2 and 4.2.2 -> 4.2.3 paths, for older Operator deployments.

I've tried to test what I can, and I believe this covers the main considerations.

There is a niche case for Tenants where the user:

1) deployed via YAML only, without specifying an image
2) Continue to upgrade MinIO Operator without every modifying that Tenant YAML again
3) Have their Tenants upgraded along with the Operator

However, this should only be an issue for very old Tenants deployed specifically via CLI. At most we might add something to the 3.X.X upgrade path to ask users to make those fixes themselves, but the included step to upgrade to latest stable should resolve this regardless.

Staged view is available in the #minio-docs channel

2022-10-11 14:21 UTC, ravindk89 commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +            fsGroup: 0
```suggestion
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              fsGroup: 0
```

2022-10-11 14:21 UTC, ravindk89 commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +            fsGroup: 0
```suggestion
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              fsGroup: 0
```

2022-10-11 14:22 UTC, ravindk89 commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +            fsGroup: 0
Looks like the YAML in general got messed up. Will fix.

2022-10-11 17:08 UTC, djwfyi requested changes
Can we get the dummy text in the screenshot to have a version later than last February?

I also suggest doing something to break out the prerequisites from the procedures a bit more. They run together visually right now.

And some other fixes and suggestions throughout. I'll take another pass at it.

2022-10-11 17:08 UTC, djwfyi commented on source/reference/kubectl-minio-plugin/kubectl-minio-init.rst
> +You can also use this command to upgrade an existing Operator installation to the version of the plugin.
This sentence reads awkward to me.
Maybe strike the last part `to the version of the plugin.`?

> You can also use this command to upgrade an Operator installation to a later version that matches the plugin.

I dunno. But that's a suggestion.

2022-10-11 23:29 UTC, Alevsk approved these changes

2022-10-11 23:36 UTC, Alevsk requested changes

2022-10-11 23:36 UTC, Alevsk commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +      - Ensure each ``tenant.spec.zones`` element has a ``names`` field set to the name for that zone.
```suggestion
      - Ensure each ``tenant.spec.zones`` element has a ``name`` field set to the name for that zone.
```

2022-10-11 23:36 UTC, Alevsk commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +      - Ensure each ``tenant.spec.zones`` element has a ``names`` field set to the name for that zone.
this one should be singular i think

2022-10-12 15:12 UTC, djwfyi approved these changes
One fix, one heading suggestion.
And some unintended CSS inheritance from the style you added.

Otherwise, LGTM.

2022-10-12 15:12 UTC, djwfyi commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +      - Ensure each ``tenant.spec.zones`` element has a ``names`` field set to the name for that zone.
These two bullet points are also being bolded by the new css you added.

2022-10-12 15:18 UTC, djwfyi commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +1. (Optional) Update each MinIO Tenant to the latest stable MinIO Version.
There are some unintended consequences of the new CSS.

2022-10-12 15:19 UTC, djwfyi commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +1. (Optional) Update each MinIO Tenant to the latest stable MinIO Version.
But the italicizing worked out well even with the bolding.

2022-10-12 15:19 UTC, djwfyi commented on source/operations/install-deploy-manage/upgrade-minio-operator.rst
> +This procedure upgrades MinIO Operator 3.X.X deployments to Operator 4.2.2.
New approach is good 👍

2022-10-12 16:03 UTC, ravindk89 commented on source/_static/scss/includes/_reset.scss
> +   ol li p:first-of-type {
Fixed!

2022-10-12 16:08 UTC, merged