DOCS-677: Update site replication recovery procedure
minio/docs pull request #694
Opened 2023-01-05 22:17 UTC by ravindk89

Closes #677 

Updates the site replication recovery tutorial with slight tweaks to the multi-site expansion tutorial to account for the latest changes to MinIO/MC

Staged:

- http://192.241.195.202:9000/staging/DOCS-677/linux/operations/install-deploy-manage/multi-site-replication.html#expand-site-replication
- http://192.241.195.202:9000/staging/DOCS-677/linux/operations/data-recovery/recover-after-site-failure.html

2023-01-05 23:10 UTC, djwfyi approved these changes
Mostly fine. I would maybe take a bit to explain why you don't really mention `charlie` in the recover from site failure example, and that site replication will take care of it. It threw me off when none of the commands mention the third site.

A couple of grammar or spelling /typo nits.

But otherwise, LGTM.

2023-01-05 23:10 UTC, djwfyi commented on source/operations/data-recovery/recover-after-site-failure.rst
> +   For example, consider a site replication configuration with three peer sites: ``alpha``, ``baker``, and ``charlie``.
Or maybe just note that the work will be from the ``alpha`` deployment and ``charlie`` will mostly be left to itself and will pick up the changes as part of the replication process. Assuming that's how it works.

2023-01-05 23:10 UTC, djwfyi commented on source/operations/install-deploy-manage/multi-site-replication.rst
>        The ``--force`` flag is required to removes the site from the site replication configuration.
> MinIO requires the ``--force`` flag to remove the site from the site replication configuration.

Removes the passive and fixes the `to removes` grammar error.

2023-01-05 23:36 UTC, poornas requested changes

2023-01-06 22:26 UTC, ravindk89 commented on source/operations/data-recovery/recover-after-site-failure.rst
> +   For deployments configured for site replication, plan to :ref:`test and upgrade <minio-upgrade>` all peer sites to the specified release.
I'll ditch the ambiguity and say ":minio-release:`RELEASE.2023-01-02T09-40-09Z` or later"

2023-01-06 22:44 UTC, ravindk89 commented on source/operations/data-recovery/recover-after-site-failure.rst
> +   For example, consider a site replication configuration with three peer sites: ``alpha``, ``baker``, and ``charlie``.
I believe the command updates everything in the same op, but it's enough to state it happens automatically as long as you specify one healthy site

2023-01-06 22:46 UTC, poornas commented on source/operations/data-recovery/recover-after-site-failure.rst
> +   For example, consider a site replication configuration with three peer sites: ``alpha``, ``baker``, and ``charlie``.
that's right - rm command just needs to be issued to one healthy site, it will take care of updating peers that are online

2023-01-06 23:04 UTC, merged