DOCS-872: Update condition key list
minio/docs pull request #935
Opened 2023-08-03 21:51 UTC by ravindk89

Closes #872 

Synchronizes the current list of policy actions to conditions

Used https://github.com/minio/pkg/blob/main/iam/policy/action.go and https://github.com/minio/pkg/blob/main/iam/policy/condition/keyname.go to refresh the list.

Also did some slight formatting cleanups, joined a bunch of lines, fixed a few minor linker errors.

Staged: http://192.241.195.202:9000/staging/DOCS-872/linux/administration/identity-access-management/policy-based-access-control.html#supported-s3-policy-actions

2023-08-03 22:48 UTC, feorlen commented on source/administration/identity-access-management/policy-based-access-control.rst
> +For complete information on any listed condition key, see the
Seems the second part of this sentence was eaten by a grue.

2023-08-03 22:52 UTC, feorlen requested changes
One to-be-reformatted line got accidentally nuked. Rest looks good.

2023-08-03 23:47 UTC, feorlen commented on source/administration/identity-access-management/policy-based-access-control.rst
> +For complete information on any listed condition key, see the
Duh, I can just suggest it back in. Presumably it should look like this:
```suggestion
For complete information on any listed condition key, see the :iam-docs:`IAM Condition Element Documentation <reference_policies_elements_condition.html>`.
```

2023-08-04 13:49 UTC, ravindk89 commented
@feorlen suggestion committed, thanks!

2023-08-04 13:56 UTC, feorlen approved these changes
👍🏻

2023-08-04 15:30 UTC, djwfyi approved these changes
LGTM

2023-08-07 16:33 UTC, ravindk89 commented
@donatello feel free to issue corrections in this PR and I will merge them up later.

2023-08-07 16:33 UTC, merged