DOCS-898: Synchronous Bucket Notifications, config API secret redaction
minio/docs pull request #960
Opened 2023-08-18 13:41 UTC by ravindk89

Closes #898 

- Adds a short section on synchronous vs asynchronous bucket notifications
- Adds a note on specific configs which now return redacted data on `mc admin config get`
- Found a few new webhook lambda envvars to add

ToDo:

- Add a short section on bucket notification queue behavior and how sync/async affects it

STAGED

- http://192.241.195.202:9000/staging/DOCS-898/linux/administration/monitoring/bucket-notifications.html#asynchronous-vs-synchronous-bucket-notifications
- http://192.241.195.202:9000/staging/DOCS-898/linux/reference/minio-server/minio-server.html#envvar.MINIO_API_SYNC_EVENTS
- http://192.241.195.202:9000/staging/DOCS-898/linux/reference/minio-mc-admin/mc-admin-config.html#mc-conf.api.sync_events
- http://192.241.195.202:9000/staging/DOCS-898/linux/reference/minio-mc-admin/mc-admin-config.html#mc-conf.notify_nats.password

2023-08-18 13:51 UTC, ravindk89 commented on source/administration/monitoring/bucket-notifications.rst
> +.. important::
http://192.241.195.202:9000/staging/DOCS-898/linux/administration/monitoring/bucket-notifications.html#asynchronous-vs-synchronous-bucket-notifications

@Praveenrajmani LMK if this is too heavy-handed.

2023-08-18 16:24 UTC, djwfyi requested changes
Suggestion for reworking the section on the bucket notification page.

All the other changes look good.

2023-08-18 16:24 UTC, djwfyi commented on source/administration/monitoring/bucket-notifications.rst
Maybe instead:

```
.. versionadded:: RELEASE.2023-06-23T20-26-00Z

   You can enable synchronous bucket notification behavior for *all* remote targets, where MinIO waits for the configured remote to confirm successful receipt before continuing to the next event.

MinIO can perform delivery of bucket notification events to remote targets either asynchronously (default) or synchronously.
The option is set at the cluster level for all remote targets.
It is *not* possible to configure some targets for asynchronous delivery and others for synchronous delivery.

With asynchronous delivery, MinIO fires the event at the configured remote and does *not* wait for a response before continuing to the next event.
If you enable synchronous delivery, MinIO fires the event at the configured remote and then waits for the remote to confirm a successful receipt before continuing to the next event.

There are considerations for each option:

- With the default asynchronous delivery, there is some risk that notifications may be lost should the remote target restart or experience another transient issue during the event transit or processing.
- With synchronous delivery, there is the possibility that the notification queue becomes full while waiting for events to process.
  If the queue reaches the configured capacity (defaults to 10,000), MinIO discards any new events.
  This means that some new events may be lost when configured for synchronous delivery.

To enable synchronous bucket notifications for *all configured remote targets*, use either of the following settings:

- Set the :envvar:`MINIO_API_SYNC_EVENTS` environment variable to ``on`` and restart the MinIO deployment.

- Set the :mc-conf:`api.sync_events` configuration setting to ``on`` and restart the MinIO deployment.
```

2023-08-18 19:36 UTC, djwfyi approved these changes
LGTM!

2023-08-18 19:55 UTC, feorlen approved these changes
👍🏻

2023-08-18 19:58 UTC, ravindk89 commented on source/administration/monitoring/bucket-notifications.rst
> +   For asynchronous or synchronous bucket notifications, MinIO discards new events if the queue fills.
@Praveenrajmani @kannappanr LMK if this is actually factually incorrect in some way. If not I'll merge this up.

2023-08-21 15:19 UTC, ravindk89 commented
Merging. @Praveenrajmani @kannappanr if the section on bucket notif behavior on full queue is incorrect let me know and we will fix.

2023-08-21 15:19 UTC, merged