Documents the scanner.speed config and minio_scanner_speed envvar
minio/docs pull request #973
Opened 2023-08-28 21:00 UTC by djwfyi

Closes #796

Staged:

- http://192.241.195.202:9000/staging/speed/linux/reference/minio-mc-admin/mc-admin-config.html#scanner
- http://192.241.195.202:9000/staging/speed/linux/reference/minio-server/minio-server.html#envvar.MINIO_SCANNER_SPEED

And a few other paragraphs here there and yon.

2023-08-28 22:03 UTC, ravindk89 requested changes
Mostly ideas to tighten/make consistent the language and try to create a 'scale' language to describe how these work. Thoughts:

- Either use 'wait time' or 'delay', not both.
- Try to use similar scalars since we are being generic
- I thought the `"add"` language might imply additive rather than a hard-set value.

I experimented with None -> short - moderate -> medium -> large wait times. 

Could also use your original language and do something like

None -> small -> moderate -> medium -> long delay

2023-08-29 15:18 UTC, ravindk89 approved these changes
LGTM mod nit

2023-08-29 15:18 UTC, ravindk89 commented on source/includes/common/scanner.rst
> +       This setting may result in reduced read/write performance for IOPS-limited systems.
Nit - thinking about it we can just mirror `fast` here and call it done w.r.t. the IOPS bit.

2023-08-29 15:18 UTC, ravindk89 commented on source/includes/common/scanner.rst
> +       This setting may result in reduced read/write performance for IOPS-limited systems.
```suggestion
       This setting may result in reduced read and write performance.
```

2023-08-29 15:21 UTC, feorlen approved these changes

2023-08-29 15:49 UTC, merged